import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {useState} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [email, setEmail] = useState('')
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={async (e) => {
          e.preventDefault()

          const response = await fetch('/api/magic', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json'
            },
            body: JSON.stringify({
              email
            })
          })
          const data = await response.json()
          window.location.href = data.redirect
        }}>
          <input type={'email'} value={email} onChange={e => setEmail(e.target.value)}/>
          <button type={'submit'}>Submit</button>
        </form>
      </main>
    </>
  )
}
